version: '3.3'
services:
  node:
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./
        target: /server
    networks:
      - panelinha-de-es

  mongo:
    build:
      context: .
      dockerfile: .docker/mongo.dockerfile
    ports:
      - "3000:27017"
    volumes:
      - "/data/mongodb:/data/db"
    networks:
      - panelinha-de-es

networks:
  panelinha-de-es: